In [1]:
import numpy as np

In [3]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [4]:
array_list = np.array(object = list_)

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [12]:
# Yes there is a difference, the variable list_ is a list whereas variable array_list is an array

In [13]:
array_list.dtype

dtype('<U1')

In [14]:
type(list_)

list

# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [15]:
list_

['1', '2', '3', '4', '5']

In [18]:
for i in list_:
    print(i , type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [19]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [20]:
for i in array_list:
    print(i, type(i))

1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:

In [21]:
array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [22]:
list_

['1', '2', '3', '4', '5']

In [23]:
for i in list_:
    print(i , type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [24]:
for i in array_list:
    print(i, type(i))

1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


# Yes, the changes can be seen easily, the data elements of variable list_ remains the same as string whereas the type of data element changed to numpy int for data elements in variable array_list

# Consider the below code to answer further questions:

In [26]:
import numpy as np

In [27]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [28]:
num_array = np.array(object = num_list)

In [29]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [30]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

 # Q4. Write a code to find the following characteristics of variable, num_array:

# (i) Shape & (ii) Size

### For num_array

In [33]:
num_array.shape

(2, 3)

In [34]:
num_array.size

6

### For num_list

In [36]:
len(num_list)

2

In [37]:
# Both shape and size of the list is 2

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [39]:
arr = np.zeros((3,3))

In [40]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
arr.shape

(3, 3)

In [42]:
arr.size

9

# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [45]:
arr1= np.eye(5)

In [47]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
arr1.shape

(5, 5)